### PR TITLE
A span element added to possible size texts

### PR DESCRIPTION
**Pull request by nomasi**
* to insure uppercaseness that can be easily overruled by css
* and other styling options too

### CODE REVIEW

**Comment by nomasi** [comment]
I'm not sure that this was very beautiful react-js.  I just wanted to add a single span element to the size string, so that it can be styled with css and possibly per retailer.

**Comment by nomasi** [comment]
I had to add one dangerouslySetInnerHTML which felt dangerous.  

All in all, I guess it's better that there are no html tags in the i18n strings?

**Comment by tjjalava** [comment]
yep, I'd guess the "react-gods" would crucify you for such abomination like string-concatenating html :stuck_out_tongue_winking_eye:

Seriously, when you have to use "dangerouslySetInnerHTML", you're probably doing something wrong. I'd use it only for some really simple html, like surrounding individual words with presentational tags. In this case, it would be better to split the localized message so that you can add the div in the middle of it, and maybe create a small react-component to make it pretty.

Or, check this out: https://react.i18next.com/components/trans-component.html. That's how you do it "i18next"-style.

**Comment by nomasi** [comment]
Hey, sorry.  This trans component seems to help nesting stuff in code and I was really happy that the code didn't have any UI strings in it.  Now the "We recommend size..." string is in both en.json and SizingBar.jsx and that isn't nice.  

If it's not a big deal, let's roll this back to how it was.  With the <strong> tags in the i18n string and all.  If the retailer doesn't like the emphasis in the default strings, they can override them with the additionalTranslations option anyway.  I didn't remember that before.

**Comment by tjjalava** [comment]
The string in SizingBar.jsx is just a template to set up the correct jsx-elements. It could just as well have just the <span>sizename<span>, all other texts are overwritten by the string in en/fi/sv.json. Good thing about the trans-tag is that we don’t need the ”dangerouslySetHtml”, but of course the customization of the translation becomes harder. Anyways, either way is fine by me.

**Pull request closed without merging**
